name: gtocp
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0-212.0.dev

# Add regular dependencies here.
dependencies:
  google_generative_ai: ^0.2.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
